routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('emprunts', 'EmpruntController');
Route::resource('exemplaires', 'ExemplaireController');
Route::resource('oeuvres', 'OeuvreController');
Route::resource('reservations', 'ReservationController');
Route::resource('usagers', 'UsagerController');

Route::get('/', function() {
    return redirect()->route('usagers.index');
})->name('home');

app/Usager.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Usager extends Model
{
    function getReservations() {
        return $this->hasMany('App\Reservation', 'Usager', 'id');
    }

    function getEmprunts() {
        return $this->hasMany('App\Emprunt', 'Usager', 'id');
    }

    function Editer($nom, $prenom) {
        $this->nom = $nom;
        $this->prenom = $prenom;
        $this->save();
    }
}

app/Http/Controllers/UsagerController.php
<?php

namespace App\Http\Controllers;

use App\Exemplaire;
use App\Usager;
use Illuminate\Http\Request;

class UsagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usagers = Usager::orderBy('nom')->get();
        return view('bibal/usagers/index', compact(
            'usagers'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $usager = new Usager;
        return view('bibal/usagers/create', compact('usager'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $usager = new Usager();
        $usager->nom = $request->get('nom');
        $usager->prenom = $request->get('prenom');
        $usager->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Usager  $usager
     * @return \Illuminate\Http\Response
     */
    public function show(Usager $usager)
    {
        return view('bibal/usagers/show', compact(
            'usager'
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Usager  $usager
     * @return \Illuminate\Http\Response
     */
    public function edit(Usager $usager)
    {
        return view('bibal/usagers/edit', compact(
            'usager'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Usager  $usager
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Usager $usager)
    {
        $usager->Editer($request->get('nom'), $request->get('prenom'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Usager  $usager
     * @return \Illuminate\Http\Response
     */
    public function destroy(Usager $usager)
    {
        // Suppression des réservations
        foreach ($usager->getReservations as $reservation) $reservation->delete();

        foreach ($usager->getEmprunts as $emprunt) {
            // Tous les exemplaires actuellement empruntés : rendre disponibles
            $exemplaire = Exemplaire::find($emprunt->getExemplaire->id);
            $exemplaire->disponible = true;
            $exemplaire->save();

            // Suppression des emprunts
            $emprunt->delete();
        }
        $usager->delete();
    }
}

resources/views/bibal/usagers/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Usagers - Ajouter</li>
    </ol>


    <div class="row">
        {{ Form::model($usager, array('onsubmit' => 'event.preventDefault(); ajouterIHM();')) }}
            {{ Form::label('nom', 'Nom') }}
            {{ Form::text('nom') }}
            {{ Form::label('prenom', 'Prénom') }}
            {{ Form::text('prenom') }}
            {{ Form::submit('Ajouter l\'usager') }}
        {{ Form::close() }}
    </div>
    <script>
        function ajouterIHM() {
            $.ajax({
                url: '{{ route('usagers.store') }}',
                data: $("form").serialize(),
                type: 'POST',
                success: function(result) {
                    window.location.replace('{{ route('usagers.index') }}');
                }
            });
        }
    </script>
@endsection

resources/views/bibal/usagers/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Usagers - Modifier</li>
    </ol>


    <div class="row">
        {{ Form::model($usager, array('onsubmit' => 'event.preventDefault(); modifierIHM();')) }}
            {{ Form::label('nom', 'Nom') }}
            {{ Form::text('nom') }}
            {{ Form::label('prenom', 'Prénom') }}
            {{ Form::text('prenom') }}
            {{ Form::submit('Modifier l\'usager') }}
        {{ Form::close() }}
    </div>
    <div class="row">
        <br><br>
        <a class="btn btn-warning" onclick="supprimerIHM()" id="toggleNavPosition">Supprimer l'usager</a>
    </div>

    <script>
        function modifierIHM() {
            $.ajax({
                url: '{{ route('usagers.update', ['usager' => $usager->id]) }}',
                data: $("form").serialize(),
                type: 'PUT',
                success: function(result) {
                    window.location.replace('{{ route('usagers.show', ['usager' => $usager->id]) }}');
                }
            });
        }
        function supprimerIHM() {
            $.ajax({
                url: '{{ route('usagers.destroy', ['usager' => $usager->id]) }}',
                data: { "_token": "{{ csrf_token() }}"},
                type: 'DELETE',
                success: function(result) {
                    window.location.replace('{{ route('usagers.index') }}');
                }
            });
        }
    </script>
@endsection

resources/views/bibal/usagers/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Usagers</li>
    </ol>


    <div class="row">
        <div class="col-3">
            <a class="btn btn-primary btn-block" onclick="ajouterUsagerIHM()"><i class="fa fa-plus fa-fw" aria-hidden="true"></i>Ajouter un usager</a><br>
            <script>
                function ajouterUsagerIHM() {
                    window.location.replace("{{ route('usagers.create') }}");
                }
            </script>
        </div>
        <div class="col-12">
            <div class="card mb-3">
                <div class="card-header">
                    <i class="fa fa-table fa-fw" aria-hidden="true"></i>Usagers
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Nom / prénom</th>
                            <th>Réservations</th>
                            <th>Emprunts</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach($usagers as $usager)
                                <tr>
                                    <td><a style="color:#0056b3; cursor: pointer" onclick="afficherUsagerIHM('{{ route('usagers.show', ['usager' => $usager->id]) }}')">{{ $usager->nom }} {{ $usager->prenom }}</a></td>
                                    <td>{{ count($usager->getReservations) }}</td>
                                    <td>{{ count($usager->getEmprunts) }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                        <script>
                            function afficherUsagerIHM(url) {
                                window.location.replace(url);
                            }
                        </script>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bibal/usagers/show.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('usagers.index') }}">Usagers</a>
        </li>
        <li class="breadcrumb-item active">{{ $usager->nom }} {{ $usager->prenom }}</li>
    </ol>

    <h1><i class="fa fa-user fa-fw" aria-hidden="true"></i>{{ $usager->nom }} {{ $usager->prenom }}</h1>
    <p><small><a onclick="editerUsagerIHM()"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i>Modifier / supprimer</a></small></p>
    <script>
        function editerUsagerIHM() {
            window.location.replace("{{ route('usagers.edit', ['usager' => $usager->id]) }}");
        }
    </script>



    <div class="row">
        <div class="col-6">
            <div class="card-header">
                <i class="fa fa-table"></i> Réservations <a onclick="reserverOeuvreIHM()">+ Ajouter</a>
                <script>
                    function reserverOeuvreIHM() {
                        window.location.replace("{{ route('reservations.create') }}");
                    }
                </script>
            </div>
            <div class="card-body">
                @if(count($usager->getReservations))
                <table class="table">
                    <thead>
                        <th>Date</th>
                        <th>Oeuvre</th>
                        <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach($usager->getReservations as $reservation)
                        <tr>
                            <td>
                                <a href="{{ route('reservations.show', ['reservation' => $reservation->id]) }}">{{ \Carbon\Carbon::parse($reservation->date)->format('d/m/Y') }}</a>
                            </td>
                            <td>
                                <a href="{{ route('oeuvres.show', ['oeuvre' => $reservation->getOeuvre->id]) }}">{{ $reservation->getOeuvre->titre }} ({{ $reservation->getOeuvre->auteur }})</a>
                            </td>
                            <td>
                                <a class="btn btn-danger" onclick="annulerReservationIHM({{ $reservation->id }})" id="toggleNavPosition">Annuler</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                @else
                <h3><i>Aucune réservation</i></h3>
                @endif
            </div>
        </div>
        <div class="col-6">
            <div class="card-header">
                <i class="fa fa-table"></i> Emprunts <a onclick="emprunterExemplaireIHM()">+ Ajouter</a>
                <script>
                    function emprunterExemplaireIHM() {
                        window.location.replace("{{ route('emprunts.create') }}");
                    }
                </script>
            </div>
            <div class="card-body">
                @if(count($usager->getEmprunts))
                <table class="table">
                    <thead>
                    <th>Date</th>
                    <th>Oeuvre / Exemplaire</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach($usager->getEmprunts as $emprunt)
                        <tr>
                            <td>
                                <a href="{{ route('emprunts.show', ['emprunt' => $emprunt->id]) }}">{{ \Carbon\Carbon::parse($emprunt->date)->format('d/m/Y') }}</a>
                            </td>
                            <td>
                                <a href="{{ route('oeuvres.show', ['oeuvre' => $emprunt->getExemplaire->getOeuvre->id]) }}">{{ $emprunt->getExemplaire->getOeuvre->titre }} ({{ $emprunt->getExemplaire->getOeuvre->auteur }})</a> / #{{ $emprunt->getExemplaire->reference }}
                            </td>
                            <td>
                                <a class="btn btn-warning" onclick="rendreExemplaireIHM({{ $emprunt->id }})" id="toggleNavPosition">Rendre</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                @else
                    <h3><i>Aucun emprunt</i></h3>
                @endif
            </div>
        </div>
    </div>
    <script>
        function annulerReservationIHM(idReservation) {
            $.ajax({
                url: '/reservations/'+idReservation,
                data: { "_token": "{{ csrf_token() }}"},
                type: 'DELETE',
                success: function(result) {
                    window.location.reload();
                }
            });
        }
        function rendreExemplaireIHM(idEmprunt) {
            $.ajax({
                url: '/emprunts/'+idEmprunt,
                data: { "_token": "{{ csrf_token() }}"},
                type: 'DELETE',
                success: function(result) {
                    window.location.reload();
                }
            });
        }
    </script>
@endsection