routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('emprunts', 'EmpruntController');
Route::resource('exemplaires', 'ExemplaireController');
Route::resource('oeuvres', 'OeuvreController');
Route::resource('reservations', 'ReservationController');
Route::resource('usagers', 'UsagerController');

Route::get('/', function() {
    return redirect()->route('usagers.index');
})->name('home');

app/Exemplaire.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Exemplaire extends Model
{
    function getOeuvre() {
        return $this->hasOne('App\Oeuvre', 'id' ,'Oeuvre');
    }

    function getEmprunts() {
        return $this->hasMany('App\Emprunt', 'Exemplaire');
    }

    function Editer($reference) {
        $this->reference = $reference;
        $this->save();
    }
}

app/Http/Controllers/ExemplaireController.php
<?php

namespace App\Http\Controllers;

use App\Exemplaire;
use App\Oeuvre;
use Illuminate\Http\Request;

class ExemplaireController extends Controller
{

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $exemplaire = new Exemplaire;
        $oeuvres = Oeuvre::pluck('titre', 'id');
        return view('bibal/exemplaires/create', compact(
            'exemplaire',
            'oeuvres'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $exemplaire = new Exemplaire();
        $exemplaire->reference = $request->get('reference');
        $exemplaire->Oeuvre = $request->get('id_oeuvre');
        $exemplaire->disponible = true;

        $exemplaire->save();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Exemplaire  $exemplaire
     * @return \Illuminate\Http\Response
     */
    public function edit(Exemplaire $exemplaire)
    {
        return view('bibal/exemplaires/edit', compact(
            'exemplaire'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Exemplaire  $exemplaire
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Exemplaire $exemplaire)
    {
        $exemplaire->Editer($request->get('reference'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Exemplaire  $exemplaire
     * @return \Illuminate\Http\Response
     */
    public function destroy(Exemplaire $exemplaire)
    {
        // On supprime les emprunts associés à cet exemplaire
        foreach ($exemplaire->getEmprunts as $emprunt) $emprunt->delete();
        $exemplaire->delete();
    }
}

resources/views/bibal/exemplaires/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Exemplaires - Ajouter</li>
    </ol>


    <div class="row">
        {{ Form::model($exemplaire, array('onsubmit' => 'event.preventDefault(); ajouterIHM();')) }}
            <p>
                {{ Form::label('reference', 'Référence') }}
                {{ Form::text('reference') }}
            </p>
            <p>
                {{ Form::label('id_oeuvre', 'Oeuvre') }}
                {{ Form::select('id_oeuvre', $oeuvres)  }}
            </p>
            {{ Form::submit('Ajouter l\'exemplaire') }}
        {{ Form::close() }}
    </div>
    <script>
        function ajouterIHM() {
            $.ajax({
                url: '{{ route('exemplaires.store') }}',
                data: $("form").serialize(),
                type: 'POST',
                success: function(result) {
                    window.location.replace('/oeuvres/'+$( "[name='id_oeuvre']" ).find(":selected").val());
                }
            });
        }
    </script>
@endsection

resources/views/bibal/exemplaires/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Exemplaire - Modifier</li>
    </ol>
    <div class="row">
        {{ Form::model($exemplaire, array('onsubmit' => 'event.preventDefault(); modifierIHM();')) }}
            {{ Form::label('reference', 'Référence') }}
            {{ Form::text('reference') }}
            {{ Form::submit('Modifier l\'exemplaire') }}
        {{ Form::close() }}
    </div>
    <div class="row">
        <br><br>
        <a class="btn btn-warning" onclick="supprimerIHM()" id="toggleNavPosition">Supprimer l'exemplaire</a>
    </div>

    <script>
        function modifierIHM() {
            $.ajax({
                url: '{{ route('exemplaires.update', ['exemplaire' => $exemplaire->id]) }}',
                data: $("form").serialize(),
                type: 'PUT',
                success: function(result) {
                    window.location.replace('{{ route('oeuvres.show', ['oeuvre' => $exemplaire->getOeuvre->id]) }}');
                }
            });
        }
        function supprimerIHM() {
            $.ajax({
                url: '{{ route('exemplaires.destroy', ['exemplaire' => $exemplaire->id]) }}',
                data: { "_token": "{{ csrf_token() }}"},
                type: 'DELETE',
                success: function(result) {
                    window.location.replace('{{ route('oeuvres.show', ['oeuvre' => $exemplaire->getOeuvre->id]) }}');
                }
            });
        }
    </script>
@endsection