routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('emprunts', 'EmpruntController');
Route::resource('exemplaires', 'ExemplaireController');
Route::resource('oeuvres', 'OeuvreController');
Route::resource('reservations', 'ReservationController');
Route::resource('usagers', 'UsagerController');

Route::get('/', function() {
    return redirect()->route('usagers.index');
})->name('home');

app/Oeuvre.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Oeuvre extends Model
{
    function getExemplaires() {
        return $this->hasMany('App\Exemplaire', 'Oeuvre');
    }

    function getReservations() {
        return $this->hasMany('App\Reservation', 'Oeuvre');
    }
    function getEmprunts() {
        return $this->hasManyThrough(
            'App\Emprunt',
            'App\Exemplaire',
            'Oeuvre',
            'Exemplaire',
            'id',
            'id'
        );
    }

    function Editer($auteur, $titre) {
        $this->auteur = $auteur;
        $this->titre = $titre;
        $this->save();
    }

    function TrouverExemplaireDispo() {
        $exemplaireReturn = false;
        foreach ($this->getExemplaires() as $exemplaire) {
            if($exemplaire->disponible) {
                $exemplaireReturn = $exemplaire;
            }
        }
        return $exemplaireReturn;
    }
}

app/Http/Controllers/OeuvreController.php
<?php

namespace App\Http\Controllers;

use App\Oeuvre;
use Illuminate\Http\Request;

class OeuvreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oeuvres = Oeuvre::orderBy('titre')->get();
        return view('bibal/oeuvres/index', compact(
            'oeuvres'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $oeuvre = new Oeuvre();
        return view('bibal/oeuvres/create', compact('oeuvre'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $oeuvre = new Oeuvre();
        $oeuvre->titre = $request->get('titre');
        $oeuvre->auteur = $request->get('auteur');
        $oeuvre->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Oeuvre  $oeuvre
     * @return \Illuminate\Http\Response
     */
    public function show(Oeuvre $oeuvre)
    {
        return view('bibal/oeuvres/show', compact(
            'oeuvre'
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Oeuvre  $oeuvre
     * @return \Illuminate\Http\Response
     */
    public function edit(Oeuvre $oeuvre)
    {
        return view('bibal/oeuvres/edit', compact(
            'oeuvre'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Oeuvre  $oeuvre
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Oeuvre $oeuvre)
    {
        $oeuvre->Editer($request->get('auteur'), $request->get('titre'));
    }
}

resources/views/bibal/oeuvres/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Oeuvres - Ajouter</li>
    </ol>
    <div class="row">
        {{ Form::model($oeuvre, array('onsubmit' => 'event.preventDefault(); ajouterIHM();')) }}
            {{ Form::label('auteur', 'Auteur') }}
            {{ Form::text('auteur') }}
            {{ Form::label('titre', 'Titre') }}
            {{ Form::text('titre') }}
            {{ Form::submit('Ajouter l\'oeuvre') }}
        {{ Form::close() }}
    </div>
    <script>
        function ajouterIHM() {
            $.ajax({
                url: '{{ route('oeuvres.store') }}',
                data: $("form").serialize(),
                type: 'POST',
                success: function(result) {
                    window.location.replace('{{ route('oeuvres.index') }}');
                }
            });
        }
    </script>
@endsection

resources/views/bibal/oeuvres/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Oeuvre - Modifier</li>
    </ol>
    <div class="row">
        {{ Form::model($oeuvre, array('onsubmit' => 'event.preventDefault(); modifierIHM();')) }}
            {{ Form::label('auteur', 'Auteur') }}
            {{ Form::text('auteur') }}
            {{ Form::label('titre', 'Titre') }}
            {{ Form::text('titre') }}
            {{ Form::submit('Modifier l\'oeuvre') }}
        {{ Form::close() }}
    </div>
    <script>
        function modifierIHM() {
            $.ajax({
                url: '{{ route('oeuvres.update', ['oeuvre' => $oeuvre->id]) }}',
                data: $("form").serialize(),
                type: 'PUT',
                success: function(result) {
                    window.location.replace('{{ route('oeuvres.show', ['oeuvre' => $oeuvre->id]) }}');
                }
            });
        }
    </script>
@endsection

resources/views/bibal/oeuvres/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item active">Oeuvres</li>
    </ol>


    <div class="row">
        <div class="col-3">
            <a class="btn btn-primary btn-block" onclick="ajouterIHM()"><i class="fa fa-plus fa-fw" aria-hidden="true"></i>Ajouter une oeuvre</a><br>
            <script>
                function ajouterIHM() {
                    window.location.replace('{{ route('oeuvres.create') }}');
                }
            </script>
        </div>
        <div class="col-12">
            <div class="card mb-3">
                <div class="card-header">
                    <i class="fa fa-table fa-fw" aria-hidden="true"></i>Oeuvres
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Auteur - Titre</th>
                            <th>Exemplaires</th>
                            <th>Emprunts</th>
                            <th>Réservations</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($oeuvres as $oeuvre)
                            <tr>
                                <td><a style="color:#0056b3; cursor: pointer" onclick="afficherOeuvreIHM('{{ route('oeuvres.show', ['oeuvre' => $oeuvre->id]) }}')">{{ $oeuvre->auteur }} - {{ $oeuvre->titre }}</a></td>
                                <td>{{ count($oeuvre->getExemplaires) }}</td>
                                <td>{{ count($oeuvre->getEmprunts) }}</td>
                                <td>{{ count($oeuvre->getReservations) }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                        <script>
                            function afficherOeuvreIHM(url) {
                                window.location.replace(url);
                            }
                        </script>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bibal/oeuvres/show.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Bibal</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('oeuvres.index') }}">Oeuvres</a>
        </li>
        <li class="breadcrumb-item active">{{ $oeuvre->titre }} ({{ $oeuvre->auteur }})</li>
    </ol>

    <h1><i class="fa fa-book fa-fw" aria-hidden="true"></i>{{ $oeuvre->titre }} ({{ $oeuvre->auteur }})</h1>
    <p><small><a onclick="editerOeuvreIHM()"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i>Modifier</a></small></p>
    <script>
        function editerOeuvreIHM() {
            window.location.replace('{{ route('oeuvres.edit', ['oeuvre' => $oeuvre->id]) }}');
        }
    </script>


    <div class="row">
        <div class="col-6">
            <div class="card-header">
                <i class="fa fa-table"></i> Réservations
            </div>
            <div class="card-body">
                @if(count($oeuvre->getReservations))
                <table class="table">
                    <thead>
                        <th>Date</th>
                        <th>Usager</th>
                    </thead>
                    <tbody>
                    @foreach($oeuvre->getReservations as $reservation)
                        <tr>
                            <td>
                                <a href="{{ route('reservations.show', ['reservation' => $reservation->id]) }}">{{ \Carbon\Carbon::parse($reservation->date)->format('d/m/Y') }}</a>
                            </td>
                            <td>
                                <a href="{{ route('usagers.show', ['usager' => $reservation->getUsager->id]) }}">{{ $reservation->getUsager->nom }} {{ $reservation->getUsager->prenom }}</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                @else
                <h3><i>Aucune réservation</i></h3>
                @endif
            </div>
        </div>
        <div class="col-6">
            <div class="card-header">
                <i class="fa fa-table"></i> Exemplaires <a onclick="ajouterExemplaireIHM()">+ Ajouter</a>
                <script>
                    function ajouterExemplaireIHM() {
                        window.location.replace('{{ route('exemplaires.create') }}');
                    }
                </script>
            </div>
            <div class="card-body">
                @if(count($oeuvre->getExemplaires))
                <table class="table">
                    <thead>
                    <th>Référence</th>
                    <th>Disp. ?</th>
                    <th>Usager</th>
                    <th>Actions</th>
                    </thead>
                    <tbody>
                    @foreach($oeuvre->getExemplaires as $exemplaire)
                        <tr>
                            <td>
                                {{ $exemplaire->reference }}
                            </td>
                            <td>
                                @if(!$exemplaire->disponible)
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                @else
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                @endif
                            </td>
                            <td>
                                @if($exemplaire->disponible)
                                    -
                                @else
                                    <a href="{{ route('usagers.show', ['usager' => $exemplaire->getEmprunts[0]->getUsager->id]) }}">{{ $exemplaire->getEmprunts[0]->getUsager->nom }} {{$exemplaire->getEmprunts[0]->getUsager->prenom }}</a>
                                @endif
                            </td>
                            <td>
                                <a class="btn btn-success" onclick="editerExemplaireIHM('{{ route('exemplaires.edit', ['exemplaire' => $exemplaire->id]) }}')" id="toggleNavPosition"><i class="fa fa-edit" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <script>
                        function editerExemplaireIHM(url) {
                            window.location.replace(url);
                        }
                    </script>
                </table>
                @else
                <h3><i>Aucun exemplaire</i></h3>
                @endif
            </div>
        </div>
    </div>
@endsection